<a href="https://colab.research.google.com/github/Benza1611/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np # packege สำหรับทำงานกับข้อมูลที่เป็นตัวเลข อยู่ในรูปแบบ Matrix

#Numpy Array

###สร้าง numpy araay (matrix)

In [2]:
np_a = np.array([[1,2,3],[4,5,6]]) #สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [4]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np_a.shape

(2, 3)

In [6]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

###Matrix transpose

In [7]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

###สร้าง matrix เริ่มต้น (zeros,one)

In [8]:
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np_0 = np.ones((5,6))
np_0

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
np_200 = 200*np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

###สร้าง matrix random

In [14]:
np.random.randn(5,5) #random เลขมาจาก normal distribution ที่มี mu=0 std=1

array([[-0.43552348, -0.9553863 ,  0.20472796,  0.24970132, -2.5715214 ],
       [ 0.70237143,  1.81035073,  1.32031824, -1.25433084,  0.3660282 ],
       [-0.52141762, -0.11916308, -0.34458211,  0.37721661, -0.06751865],
       [-0.64936668, -0.92746038,  0.56099862, -0.34100765, -0.58027705],
       [ 0.21470551,  0.98987324,  0.46934421,  1.05365293,  2.00320905]])

In [15]:
2+(5*np.random.randn(3,3)) #random เลขมาจาก normal distribution ที่มี mu=2 std=5

array([[-12.91365247,   7.76610235,   4.41813754],
       [  0.73807396,  -0.06970005,   1.50922152],
       [ -7.30968916,  -1.15348134,   4.65476009]])

In [17]:
np.random.randint(5,11,(4,5)) # random เลขจำนวนเต็ม ระหว่าง [5-11) ขนาด (4*5)

array([[ 9, 10,  9,  7,  7],
       [ 6,  9,  5,  7,  7],
       [ 8,  9, 10,  7, 10],
       [ 5,  6,  7,  9, 10]])