<a href="https://colab.research.google.com/github/Benza1611/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np # packege สำหรับทำงานกับข้อมูลที่เป็นตัวเลข อยู่ในรูปแบบ Matrix

#Numpy Array

###สร้าง numpy araay (matrix)

In [6]:
np_a = np.array([[1,2,3],[4,5,6]]) #สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [7]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np_a.shape

(2, 3)

In [9]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

###Matrix transpose

In [10]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

###สร้าง matrix เริ่มต้น (zeros,one)

In [11]:
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np_0 = np.ones((5,6))
np_0

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [13]:
np_200 = 200*np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

###สร้าง matrix random

In [14]:
np.random.randn(5,5) #random เลขมาจาก normal distribution ที่มี mu=0 std=1

array([[-0.76290748,  0.50202175,  1.40738352, -0.46608143,  0.67717533],
       [-0.20639583, -0.24298903,  0.46025218, -1.89887388,  1.47989826],
       [-0.54883227, -0.86300749, -0.49241394, -0.50440281, -0.31292105],
       [-0.89698347,  0.14653688, -1.03807565, -0.32464521, -1.28420657],
       [ 0.40794103,  0.27232999, -0.92193058, -0.22173593,  1.7183383 ]])

In [15]:
2+(5*np.random.randn(3,3)) #random เลขมาจาก normal distribution ที่มี mu=2 std=5

array([[-6.6601925 ,  5.66541952,  8.71042352],
       [-2.7624085 ,  3.2649995 ,  0.10448071],
       [ 0.86812925, -5.84574682,  2.80387414]])

In [16]:
np.random.randint(5,11,(4,5)) # random เลขจำนวนเต็ม ระหว่าง [5-11) ขนาด (4*5)

array([[ 6,  8, 10,  6,  5],
       [ 5, 10,  9,  6,  9],
       [ 5,  6,  7,  9,  7],
       [ 7, 10, 10,  8,  5]])

###matrix properties

In [17]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
np_a.T # transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [21]:
1+np_a #add scalar to matrix

array([[2, 3, 4],
       [5, 6, 7]])

In [22]:
2*np_a #multiply scalar to matrix

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [23]:
np_c = np.array([[6,5,4],[3,2,1]])
np_c

array([[6, 5, 4],
       [3, 2, 1]])

In [24]:
np_a + np_c # adding matrix to matrix

array([[7, 7, 7],
       [7, 7, 7]])

In [25]:
np_a.shape

(2, 3)

In [26]:
np_c.shape

(2, 3)

In [30]:
np_c.T.shape

(3, 2)

In [31]:
np.dot(np_a,np_c.T) # multipling matrix to mxtrix (a,b) x (b,c) = (a,c)

array([[28, 10],
       [73, 28]])

#Indexing & Slicing

In [32]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
np_a[1,1]

5

In [35]:
np_a[:2,:2]

array([[1, 2],
       [4, 5]])

In [36]:
np_a[0,:]

array([1, 2, 3])

#Useful functions

In [37]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
np.sum(np_a)

21

In [45]:
np.sum(np_a,axis=0) # axis=0 ก็คือรวมเลขในแต่ละแถว

array([5, 7, 9])

In [46]:
np.sum(np_a,axis=1) # axis=1 ก็คือรวมเลขในแต่ละหลัก

array([ 6, 15])

In [47]:
np.mean(np_a)

3.5

In [44]:
np.mean(np_a,axis=0) #หาค่า mean ของ column

array([2.5, 3.5, 4.5])

#วน loop เอง


###Summation

In [51]:
np_a.shape

(2, 3)

In [50]:
sum_all = 0

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all = sum_all + np_a[row,col]
        print(f'we are at row= {row}, col= {col}  np_a[{row},{col}] = {np_a[row,col]} sum_all = {sum_all}')
print(sum_all)

we are at row= 0, col= 0  np_a[0,0] = 1 sum_all = 1
we are at row= 0, col= 1  np_a[0,1] = 2 sum_all = 3
we are at row= 0, col= 2  np_a[0,2] = 3 sum_all = 6
we are at row= 1, col= 0  np_a[1,0] = 4 sum_all = 10
we are at row= 1, col= 1  np_a[1,1] = 5 sum_all = 15
we are at row= 1, col= 2  np_a[1,2] = 6 sum_all = 21
21




```
np.sum(np_a,axis=0)
```



In [53]:
sum_all = np.zeros(np_a.shape[1])

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[col] = sum_all[col] + np_a[row,col]
        
print(sum_all)

[5. 7. 9.]


#Quiz กลุ่ม

วนลูปหาค่า

* ```np.sum(np_a,axis=1)```
* ```np.mean(np_a)```
* ```np.mean(np_a,axis=0)```
* ```np.mean(np_a,axis=1)```

#ข้อ5

In [58]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
max_a = 0


for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        if max_a >= 0:
            max_a =np_a[row,col]
print(max_a)

6
